### ISSUE TITLE
Site http://www.umleditor.org/index.html

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/umleditor#36]
The site http://www.umleditor.org/index.html seem to be a little bit outdated ...

Will it be refreshed or redirected or retired or stay unchanged?

**Comment by beistehen** [comment]
Starting in 2021 documentation of all INTERLIS related tools listed on https://www.interlis.ch will be reviewed and updated.
Stay tuned!

**Comment by Pierre-de-la-Verre** [comment]
thanks
