### ISSUE TITLE
Unprecise error message

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/umleditor#37]
Importing an ILI I got the message

`08:29:18 .......sser_2012_LV95.ili:97:Duplicate EnumElement name "tot".`

**:97:** is a little bit cryptic, it should say something like

`08:29:18 ...sser_2012_LV95.ili: Definition starting on line 97 - Duplicate EnumElement name "tot".`

**Comment by claeis** [comment]
The error message is from the compiler (https://github.com/claeis/ili2c) and intentional that way, to enable parsing and error highlighting in text editors (such as http://www.jedit.org).
