### ISSUE TITLE
Eingabe von Metaattributen

### ISSUE THREAD

**Issue by edigonzales** [claeis/umleditor#50]
Funktionsumfang circa gemäss Colombia-Fork.

**Comment by edigonzales** [comment]
- Metaattribute zum Modell (werden im Colombia-Fork nicht unterstützt)
- Metaattribute damit das ilimodels.xml mit sinnvollem Inhalt gefüllt werden kann, z.B. Tags, shortDescription

**Comment by claeis** [comment]
Import-/Export von ili-Dateien funktioniert bereits. Nur GUI fehlt.

**Comment by claeis** [comment]
@patrickackermann Fehlt noch das UI bei den einzelnen Aufzählelementen
