### ISSUE TITLE
Changing the language of the GUI

### ISSUE THREAD

**Issue by ltzur** [claeis/umleditor#52]
Mit dem Befehl

java -Duser.language=fr -jar umleditor-3.7.7-SNAPSHOT.jar

habe ich versucht, in der neusten SNAPSHOT-Version des UML-Editors die Sprache des GUI (Menüs etc.) auf französisch bzw. italienisch zu wechseln. Dies ist so nicht mehr möglich.
Eine andere Möglichkeit besteht über den Menüpunkt Hilfe --> Language, dies funktioniert aber nur für französisch und englisch, italienisch fehlt in der Auswahlliste.

**Comment by claeis** [comment]
Menupunkt Hilfe-->Language entfernt, weil man die Sprache nicht dynamisch umstellen kann. (Weil mit Locale.setDefault() keine statisch initialisierten Objekte geändert werden können)
