### ISSUE TITLE
Vereinfachung des Umgangs mit Zeit

### ISSUE THREAD

**Issue by claeis** [claeis/umleditor#64]

**Comment by olivergrimm** [comment]
Betrifft 2.4-Modelle / Attribut- / Domaindefinition:

Bestehende Typen _Datum, Datum inkl. Zeit, Zeit_ mit den generischen Wertebereichen DATE, DATETIME, TIMEOFDAY umsetzen.
Zudem kann in diesen Fällen im GUI auf die Wertebereichsdefinition verzichten werden (ausblenden?)

Import von 2.4-Modell mit neuen Typen verursacht aktuell eine Exception und muss ebenfalls angepasst werden. 

Testmodell: `\umleditor\testdata\datetime24\datetime24.ili`
