### ISSUE TITLE
Block comments ignored when importing model

### ISSUE THREAD

**Issue by beistehen** [claeis/umleditor#66]
According to the RefHB (2.3 and 2.4), block comments start with `/*`

UML Editor ignores comments starting with `/*` when importing an INTERLIS model. Expected behaviour is to add the comment to the comments section in the corresponding dialog. E.g. for classes:
![grafik](https://user-images.githubusercontent.com/26199857/197473420-29ae4c3d-fa95-4cba-837b-0859995d496b.png)

When changing the starting part of the block comment to `/**` (adding an additional `*`) in the model, the block comment is then imported correctly and added to the dialog. This behaviour should be corrected in a way that a regular block comment (according to the specification) is imported as well.

[model_with_correct_block_comments.ili.txt](https://github.com/claeis/umleditor/files/9849846/model_with_correct_block_comments.ili.txt)

**Comment by claeis** [comment]
block and line comments are ignored by the umleditor, except the special ilidoc comments (claeis/ili2c#66)

**Comment by sjib** [comment]
![uml_editor_beschreibung_doppelstern](https://user-images.githubusercontent.com/1265865/198282211-82cafe73-b54a-42c1-b521-13322424f37a.png)
[model_with_correct_block_comments_doppelstern.ili.txt](https://github.com/claeis/umleditor/files/9879299/model_with_correct_block_comments_doppelstern.ili.txt)
