### ISSUE TITLE
Konsistenzbedingungen (Constraints) mit Namen

### ISSUE THREAD

**Issue by claeis** [claeis/umleditor#69]

**Comment by olivergrimm** [comment]
Test mit 3.9.1: 

**Import**

- Die Anzeige des Constraint-Namens im Objektbaum klappt.

- Der Syntax wird bei Constraints mit einer Implikation im Ausdruck nach dem Import nicht korrekt umgesetzt:
  `MANDATORY CONSTRAINT CheckImplication: attr1 == #val1 => DEFINED(geom);`
  Umsetzung Syntax in UMLEditor:
  
![image](https://github.com/claeis/umleditor/assets/3465512/6c44abbf-7a63-48c6-97f3-387f84458a7d)

**Comment by claeis** [comment]
Es braucht keine Checkbox. Es kann analog wie bei den Einheiten sein. D.h. der Import übernimmt den Namen aus dem ili-Modell als Namen des Modellelementes und als Teil der Syntax. Der User ist danach selber verantwortlich diese beiden Namen konsistent zu halten (wie bei den Einheiten).  Es ist ein Problem im ili2c https://github.com/claeis/ili2c/issues/95

**Comment by claeis** [comment]
> und dass der Syntax nicht korrekt übernommen wird ist auch ein ili2c Problem?

ja (nur das ist das Problem)

**Comment by claeis** [comment]
> Das heisst der Name im Namensfeld und der vergebene Name in Syntax haben unterschiedlichen Zweck.

Nein, das ist einfach eine Folge des Kompromisses Programmier-Aufwand vs. Benutzerfreundlichkeit.

**Comment by patrickackermann** [comment]
ili2c wird in https://github.com/claeis/ili2c/pull/100 entsprechend angepasst.
Im umleditor muss die ili2c version dann angepasst werden.
