### ISSUE TITLE
NLSXML - import fails in french locale, # in path

### ISSUE THREAD

**Issue by beistehen** [claeis/umleditor#83]
## Zusammenfassung
In der französischen Benutzeroberfläche des UML/INTERLIS Editors lässt sich eine Übersetzungsdatei (NLSXML) exportieren, jedoch nicht wieder importieren.

## Schritte zum Reproduzieren
1. UML/INTERLIS Editor mit französischem GUI starten (in deutscher Systemumgebung unter Angabe von `-Duser.language=fr`).
2. Links in der Baumansicht die Vorlage _INTERLIS2Def3_ anwählen.
3. Menü _Outils -> Translation XML -> **Exporter ...**_ anwählen und Datei unter einem beliebigen Namen speichern.
4. Menü _Outils -> Translation XML -> **Importer ...**_ anwählen und die im vorangehenden Schritt gespeicherte Datei auswählen.
5. Log-Fenster zeigt folgende Meldungen:
   ```
   13:23:14 [Export Translation-XML] done
   13:23:34 Import Translation-XML failed
   13:23:34 javax.xml.bind.UnmarshalException
   13:23:34 Contenu non autorisé dans le prologue. 
   ```

## Feststellungen
* Im deutschen GUI führen obige Schritte _nicht_ zu einer Exception.
* Egal, ob das GUI in Deutsch oder Französisch ist: Die exportierten Daten (NLSXML) sind identisch.

**Comment by claeis** [comment]
Kann ich nicht reproduzieren mit umleditor-3.10.0, ili2c-5.5.3.

**Comment by beistehen** [comment]
> Kann ich nicht reproduzieren mit umleditor-3.10.2, ili2c-5.5.3.

War jedoch genau mit dieser Version:
![grafik](https://github.com/user-attachments/assets/5ae9672a-e6f1-4507-ae39-0075cc389ce1)


Kann ich `--trace` verwenden und wenn ja, wie?

**Comment by beistehen** [comment]
[trace-file + export xml.zip](https://github.com/user-attachments/files/17980861/83_trace_nlsxml.zip)

**Comment by claeis** [comment]
Kann es nicht reproduzieren mit der angehängten XML Datei. Kann es nicht reproduzieren mit einem Dateinamen der # oder ' ' oder '-' enthält.

Kannst Du mal mit einer anderen Java Version probieren?

**Comment by beistehen** [comment]
Das mit dem Dateinamen hat mich auf die Spur gebracht, danke. Nicht der Dateiname enthält ein #, sondern der Pfad! Siehe trace.log, Zeile 6 (SAXParseException).

Sobald ich die Datei an einen Ort verschoben hatte, der im Pfad _kein_ # (hashtag) hat, funktioniert der Import.
